apiVersion: v1
kind: Service
metadata:
  name: jogos-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
spec:
  type: LoadBalancer
  selector:
    app: jogos-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
